#!/bin/bash

# First run 'mysql_secure_installation'.

# The following will prompt for root password
mysql --user=root --password mysql <<EOT
CREATE USER 'lwatchclient'@'%';
GRANT SHOW DATABASES on *.* TO 'lwatchclient'@'%';
GRANT SELECT ON *.* TO 'lwatchclient'@'%';
CREATE USER 'lwatchadmin'@'localhost';
GRANT SHOW DATABASES on *.* TO 'lwatchadmin'@'localhost';
GRANT SELECT,INSERT ON *.* TO 'lwatchadmin'@'localhost';
EOT
