tparse: strskip 0: OK
tparse: strskip 1: OK
tparse: strskip 2: OK
tparse: strskip 3: OK
tparse: strskip 4: OK
tparse: strskip 0: OK
tparse: strskip 1: OK
tparse: strskip 2: OK
tparse: strskip 3: OK
tparse: strskip 4: OK
tparse: strskipcpy 1: 'foo'
tparse: strskipcpy 1: 'bar'
tparse: strskipcpy 1: 'baz'
tparse: strskipcpy 1: 'foo'
tparse: strskipcpy 1: 'bar'
tparse: strskipcpy 1: 'baz'
tparse: strappendfield: fubar;smurf
tparse: oss_v1: OK
tparse: router_v1: OK
tparse: ost_v1: OK
tparse: mds_v2: OK
tparse: mdt_v1: OK
tparse: ost_v2: OK
tparse: osc_v1: OK
tparse: lmt_mdt_v1: parse error: string not exhausted
tparse: mdt_v1(truncated): FAIL
tparse: lmt_ost_v2: parse error: string not exhausted
tparse: ost_v2(truncated): FAIL
tparse: lmt_mdt_v1: parse error: mdops
tparse: mdt_v1(elongated): FAIL
tparse: ost_v2(elongated): OK
