tparse: lmt_mdt_v1: parse error: string not exhausted
tparse: mdt_v1(truncated): FAIL
tparse: lmt_ost_v2: parse error: string not exhausted
tparse: ost_v2(truncated): FAIL
tparse: lmt_mdt_v1: parse error: mdops
tparse: mdt_v1(elongated): FAIL
tparse: ost_v2(elongated): OK
strskip 0: OK
strskip 1: OK
strskip 2: OK
strskip 3: OK
strskip 4: OK
strskip 0: OK
strskip 1: OK
strskip 2: OK
strskip 3: OK
strskip 4: OK
strskipcpy 1: 'foo'
strskipcpy 1: 'bar'
strskipcpy 1: 'baz'
strskipcpy 1: 'foo'
strskipcpy 1: 'bar'
strskipcpy 1: 'baz'
strappendfield: fubar;smurf
oss_v1: OK
router_v1: OK
ost_v1: OK
mds_v2: OK
mdt_v1: OK
ost_v2: OK
