#!/bin/bash -e

TEST=$(basename $0 | cut -d- -f1)
# test $(id -u) == 0 || exit 77 #skip if not root
../scripts/create_lmtconfig -s ../scripts/create_schema-1.1.sql \
    -f $TEST.cf -d test >$TEST.out 2>&1
diff $TEST.exp $TEST.out >$TEST.diff
