#!/bin/bash -e

TEST=$(basename $0 | cut -d- -f1)
# test $(id -u) == 0 || exit 77 #skip if not root

# Set up fake proc directory for test
tmpdir=$(mktemp -d)
mkdir -p $tmpdir/proc/fs/lustre/obdfilter/lc1-OST0000
cp brw_stats $tmpdir/proc/fs/lustre/obdfilter/lc1-OST0000

./tbrw_stats $tmpdir/proc >$TEST.out 2>&1

[ -n "$tmpdir" ] && rm -rf $tmpdir

diff $TEST.exp $TEST.out >$TEST.diff

