#!/bin/bash -e

TEST=$(basename $0 | cut -d- -f1)
# test $(id -u) == 0 || exit 77 #skip if not root

# Set up fake proc directory for test
tmpdir=$(mktemp -d)
mkdir -p $tmpdir/fs/lustre/osc/lsb-OST0000
cp proc.osc.ost_server_uuid $tmpdir/fs/lustre/osc/lsb-OST0000/ost_server_uuid

./tosc $tmpdir/ >$TEST.out 2>&1

[ -n "$tmpdir" ] && rm -rf $tmpdir

diff $TEST.exp $TEST.out >$TEST.diff

