create database filesystem_test;
connect filesystem_test;
#
# LMT2 SCHEMA 1.1 - begin
#
create table FILESYSTEM_INFO (
    FILESYSTEM_ID   integer         not null auto_increment,
    FILESYSTEM_NAME varchar(128)    not null,
    FILESYSTEM_MOUNT_NAME varchar(64) not null,
    SCHEMA_VERSION float not null,
    primary key (FILESYSTEM_ID),
    index(FILESYSTEM_ID)
);
create table OSS_INFO (
    OSS_ID          integer         not null auto_increment,
    FILESYSTEM_ID   integer         not null,
    HOSTNAME        varchar(128)    not null,
    FAILOVERHOST    varchar(128),
    foreign key(FILESYSTEM_ID) references FILESYSTEM_INFO(FILESYSTEM_ID),
    primary key (OSS_ID),
    index(OSS_ID)
);
create table OSS_INTERFACE_INFO (
    OSS_INTERFACE_ID   integer      not null auto_increment,
    OSS_ID             integer      not null,
    OSS_INTERFACE_NAME varchar(128) not null,
    EXPECTED_RATE      integer,
    primary key (OSS_INTERFACE_ID),
    index(OSS_INTERFACE_ID)
);
create table OST_INFO (
    OST_ID          integer         not null auto_increment,
    OSS_ID          integer         not null,
    OST_NAME        varchar(128)    not null,
    HOSTNAME        varchar(128)    not null,
    OFFLINE         boolean,
    DEVICE_NAME     varchar(128),
    foreign key(OSS_ID) references OSS_INFO(OSS_ID),
    primary key (OST_ID),
    index(OST_ID)
);
create table MDS_INFO (
    MDS_ID          integer         not null auto_increment,
    FILESYSTEM_ID   integer         not null,
    MDS_NAME        varchar(128)    not null,
    HOSTNAME        varchar(128)    not null,
    DEVICE_NAME     varchar(128),
    foreign key(FILESYSTEM_ID) references FILESYSTEM_INFO(FILESYSTEM_ID),
    primary key (MDS_ID),
    index(MDS_ID)
);
create table ROUTER_INFO (
    ROUTER_ID       integer         not null auto_increment,
    ROUTER_NAME     varchar(128)    not null,
    HOSTNAME        varchar(128)    not null,
    ROUTER_GROUP_ID integer         not null,
    primary key(ROUTER_ID),
    index(ROUTER_ID)
);
create table OPERATION_INFO (
    OPERATION_ID    integer         not null auto_increment,
    OPERATION_NAME  varchar(64)     not null unique,
    UNITS           varchar(16)     not null,
    primary key(OPERATION_ID),
    index(OPERATION_ID),
    index(OPERATION_NAME)
);create table TIMESTAMP_INFO (
    TS_ID           int unsigned    not null auto_increment,
    TIMESTAMP       datetime        not null,
    primary key(TS_ID),
    key(TIMESTAMP),
    index(TS_ID),
    index(TIMESTAMP)
);
create table VERSION (
    VERSION_ID      integer         not null auto_increment,
    VERSION         varchar(255)    not null,
    TS_ID           int unsigned    not null,
    primary key(VERSION_ID),
    key(TS_ID),
    foreign key(TS_ID) references TIMESTAMP_ID(TS_ID),
    index(VERSION_ID),
    index(TS_ID)
);
create table EVENT_INFO (
    EVENT_ID        integer         not null auto_increment,
    EVENT_NAME      varchar(64)     not null,
    primary key(EVENT_ID),
    index(EVENT_ID)
);
create table OST_VARIABLE_INFO (
    VARIABLE_ID     integer         not null auto_increment,
    VARIABLE_NAME   varchar(64)     not null,
    VARIABLE_LABEL  varchar(64),
    THRESH_TYPE     integer,
    THRESH_VAL1     float,
    THRESH_VAL2     float,
    primary key (VARIABLE_ID),
    key (VARIABLE_NAME),
    index(VARIABLE_ID)
);
create table OSS_VARIABLE_INFO (
    VARIABLE_ID     integer         not null auto_increment,
    VARIABLE_NAME   varchar(64)     not null,
    VARIABLE_LABEL  varchar(64),
    THRESH_TYPE     integer,
    THRESH_VAL1     float,
    THRESH_VAL2     float,
    primary key (VARIABLE_ID),
    key (VARIABLE_NAME),
    index(VARIABLE_ID)
);
create table MDS_VARIABLE_INFO (
    VARIABLE_ID     integer         not null auto_increment,
    VARIABLE_NAME   varchar(64)     not null,
    VARIABLE_LABEL  varchar(64),
    THRESH_TYPE     integer,
    THRESH_VAL1     float,
    THRESH_VAL2     float,
    primary key (VARIABLE_ID),
    key (VARIABLE_NAME),
    index(VARIABLE_ID)
);
create table ROUTER_VARIABLE_INFO (
    VARIABLE_ID     integer         not null auto_increment,
    VARIABLE_NAME   varchar(64)     not null,
    VARIABLE_LABEL  varchar(64),
    THRESH_TYPE     integer,
    THRESH_VAL1     float,
    THRESH_VAL2     float,
    primary key (VARIABLE_ID),
    key (VARIABLE_NAME),
    index(VARIABLE_ID)
);
create table OST_DATA (
    OST_ID          integer         not null comment 'OST ID',
    TS_ID           int unsigned    not null comment 'TS ID',
    READ_BYTES      bigint                   comment 'READ BYTES',
    WRITE_BYTES     bigint                   comment 'WRITE BYTES',
    PCT_CPU         float                    comment '%CPU',
    KBYTES_FREE     bigint                   comment 'KBYTES FREE',
    KBYTES_USED     bigint                   comment 'KBYTES USED',
    INODES_FREE     bigint                   comment 'INODES FREE',
    INODES_USED     bigint                   comment 'INODES USED',
    primary key (OST_ID,TS_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(TS_ID)  references TIMESTAMP_INFO(TS_ID),
    index(TS_ID),
    index(OST_ID)
    ) MAX_ROWS=2000000000;
create table OST_OPS_DATA (
    OST_ID          integer         not null comment 'OST ID',
    TS_ID           int unsigned    not null comment 'TS ID',
    OPERATION_ID    integer         not null comment 'OP ID',
    SAMPLES         bigint                   comment 'SAMPLES',
    primary key (OST_ID,TS_ID,OPERATION_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(TS_ID)  references TIMESTAMP_INFO(TS_ID),
    foreign key(OPERATION_ID)  references OPERATION_INFO(OPERATION_ID),
    index(TS_ID),
    index(OST_ID),
    index(OPERATION_ID)
    ) MAX_ROWS=2000000000;
create table OSS_DATA (
    OSS_ID          integer         not null comment 'OSS ID',
    TS_ID           int unsigned    not null comment 'TS ID',
    PCT_CPU         float                    comment '%CPU',
    PCT_MEMORY      float                    comment '%MEM',
    primary key (OSS_ID,TS_ID),
    foreign key(OSS_ID) references OSS_INFO(OSS_ID),
    foreign key(TS_ID) references TIMESTAMP_ID(TS_ID),
    index(TS_ID),
    index(OSS_ID)
);
create table OSS_INTERFACE_DATA (
    OSS_INTERFACE_ID integer        not null comment 'OSS INTER ID',
    TS_ID           int unsigned    not null comment 'TS ID',
    READ_BYTES      bigint                   comment 'READ BYTES',
    WRITE_BYTES     bigint                   comment 'WRITE BYTES',
    ERROR_COUNT     integer                  comment 'ERR COUNT',
    LINK_STATUS     integer                  comment 'LINK STATUS',
    ACTUAL_RATE     integer                  comment 'ACT RATE',
    primary key (OSS_INTERFACE_ID,TS_ID),
    foreign key(OSS_INTERFACE_ID) references OSS_INTERFACE_INFO(OSS_INTERFACE_ID),
    foreign key(TS_ID) references TIMESTAMP_ID(TS_ID),
    index(TS_ID),
    index(OSS_INTERFACE_ID)
);
create table MDS_DATA (
    MDS_ID          integer         not null comment 'MDS ID',
    TS_ID           int unsigned    not null comment 'TS ID',
    PCT_CPU         float                    comment '%CPU',
    KBYTES_FREE     bigint                   comment 'KBYTES FREE',
    KBYTES_USED     bigint                   comment 'KBYTES USED',
    INODES_FREE     bigint                   comment 'INODES FREE',
    INODES_USED     bigint                   comment 'INODES USED',
    primary key (MDS_ID,TS_ID),
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    index(TS_ID),
    index(MDS_ID)
    ) MAX_ROWS=2000000000;
create table MDS_OPS_DATA (
    MDS_ID          integer         not null comment 'OST ID',
    TS_ID           int unsigned    not null comment 'TS ID',
    OPERATION_ID    integer         not null comment 'OP ID',
    SAMPLES         bigint                   comment 'SAMPLES',
    SUM             bigint                   comment 'SUM',
    SUMSQUARES      bigint                   comment 'SUM SQUARES',
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(TS_ID)  references TIMESTAMP_INFO(TS_ID),
    foreign key(OPERATION_ID)  references OPERATION_INFO(OPERATION_ID),
    index(TS_ID),
    index(MDS_ID),
    index(OPERATION_ID)
    ) MAX_ROWS=2000000000;
create table ROUTER_DATA (
    ROUTER_ID       integer         not null comment 'ROUTER ID',
    TS_ID           int unsigned    not null comment 'TS ID',
    BYTES           bigint                   comment 'BYTES',
    PCT_CPU         float                    comment '%CPU',
    primary key (ROUTER_ID,TS_ID),
    foreign key(ROUTER_ID) references ROUTER_INFO(ROUTER_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    index(ROUTER_ID),
    index(TS_ID)
    ) MAX_ROWS=2000000000;
create table EVENT_DATA (
    EVENT_ID        integer         not null,
    TS_ID           int unsigned    not null comment 'TS ID',
    OSS_ID          integer                  comment 'OSS ID',
    OST_ID          integer                  comment 'OST ID',
    MDS_ID          integer                  comment 'MDS ID',
    ROUTER_ID       integer                  comment 'ROUTER ID',
    COMMENT         varchar(4096)            comment 'COMMENT',
    foreign key(EVENT_ID) references EVENT_INFO(EVENT_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(ROUTER_ID) references ROUTER_INFO(ROUTER_ID),
    index(EVENT_ID),
    index(TS_ID),
    index(OST_ID)
    ) MAX_ROWS=2000000000;
create table OST_AGGREGATE_HOUR (
    OST_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (OST_ID,TS_ID,VARIABLE_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(OST_ID),
    index(TS_ID),
    index(VARIABLE_ID)
    ) MAX_ROWS=2000000000;
create table OST_AGGREGATE_DAY (
    OST_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (OST_ID,TS_ID,VARIABLE_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(OST_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table OST_AGGREGATE_WEEK (
    OST_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (OST_ID,TS_ID,VARIABLE_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(OST_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table OST_AGGREGATE_MONTH (
    OST_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (OST_ID,TS_ID,VARIABLE_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(OST_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table OST_AGGREGATE_YEAR (
    OST_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (OST_ID,TS_ID,VARIABLE_ID),
    foreign key(OST_ID) references OST_INFO(OST_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(OST_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table ROUTER_AGGREGATE_HOUR (
    ROUTER_ID       integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (ROUTER_ID,TS_ID,VARIABLE_ID),
    foreign key(ROUTER_ID) references ROUTER_INFO(ROUTER_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references ROUTER_VARIABLE_INFO(VARIABLE_ID),
    index(ROUTER_ID),
    index(TS_ID),
    index(VARIABLE_ID)
    ) MAX_ROWS=2000000000;
create table ROUTER_AGGREGATE_DAY (
    ROUTER_ID       integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (ROUTER_ID,TS_ID,VARIABLE_ID),
    foreign key(ROUTER_ID) references ROUTER_INFO(ROUTER_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references ROUTER_VARIABLE_INFO(VARIABLE_ID),
    index(ROUTER_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table ROUTER_AGGREGATE_WEEK (
    ROUTER_ID       integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (ROUTER_ID,TS_ID,VARIABLE_ID),
    foreign key(ROUTER_ID) references ROUTER_INFO(ROUTER_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references ROUTER_VARIABLE_INFO(VARIABLE_ID),
    index(ROUTER_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table ROUTER_AGGREGATE_MONTH (
    ROUTER_ID       integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (ROUTER_ID,TS_ID,VARIABLE_ID),
    foreign key(ROUTER_ID) references ROUTER_INFO(ROUTER_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references ROUTER_VARIABLE_INFO(VARIABLE_ID),
    index(ROUTER_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table ROUTER_AGGREGATE_YEAR (
    ROUTER_ID       integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (ROUTER_ID,TS_ID,VARIABLE_ID),
    foreign key(ROUTER_ID) references ROUTER_INFO(ROUTER_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references ROUTER_VARIABLE_INFO(VARIABLE_ID),
    index(ROUTER_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table MDS_AGGREGATE_HOUR (
    MDS_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (MDS_ID,TS_ID,VARIABLE_ID),
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references MDS_VARIABLE_INFO(VARIABLE_ID),
    index(MDS_ID),
    index(TS_ID),
    index(VARIABLE_ID)
    ) MAX_ROWS=2000000000;
create table MDS_AGGREGATE_DAY (
    MDS_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (MDS_ID,TS_ID,VARIABLE_ID),
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references MDS_VARIABLE_INFO(VARIABLE_ID),
    index(MDS_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table MDS_AGGREGATE_WEEK (
    MDS_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (MDS_ID,TS_ID,VARIABLE_ID),
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references MDS_VARIABLE_INFO(VARIABLE_ID),
    index(MDS_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table MDS_AGGREGATE_MONTH (
    MDS_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (MDS_ID,TS_ID,VARIABLE_ID),
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references MDS_VARIABLE_INFO(VARIABLE_ID),
    index(MDS_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table MDS_AGGREGATE_YEAR (
    MDS_ID          integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    AGGREGATE       float,
    MINVAL          float,
    MAXVAL          float,
    AVERAGE         float,
    NUM_SAMPLES     integer,
    primary key (MDS_ID,TS_ID,VARIABLE_ID),
    foreign key(MDS_ID) references MDS_INFO(MDS_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references MDS_VARIABLE_INFO(VARIABLE_ID),
    index(MDS_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table FILESYSTEM_AGGREGATE_HOUR (
    FILESYSTEM_ID   integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    OST_AGGREGATE   float,
    OST_MINVAL      float,
    OST_MAXVAL      float,
    OST_AVERAGE     float,
    primary key (FILESYSTEM_ID,TS_ID,VARIABLE_ID),
    foreign key(FILESYSTEM_ID) references FILESYSTEM_INFO(FILESYSTEM_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(FILESYSTEM_ID),
    index(TS_ID),
    index(VARIABLE_ID)
    ) MAX_ROWS=2000000000;
create table FILESYSTEM_AGGREGATE_DAY (
    FILESYSTEM_ID   integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    OST_AGGREGATE   float,
    OST_MINVAL      float,
    OST_MAXVAL      float,
    OST_AVERAGE     float,
    primary key (FILESYSTEM_ID,TS_ID,VARIABLE_ID),
    foreign key(FILESYSTEM_ID) references FILESYSTEM_INFO(FILESYSTEM_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(FILESYSTEM_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table FILESYSTEM_AGGREGATE_WEEK (
    FILESYSTEM_ID   integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    OST_AGGREGATE   float,
    OST_MINVAL      float,
    OST_MAXVAL      float,
    OST_AVERAGE     float,
    primary key (FILESYSTEM_ID,TS_ID,VARIABLE_ID),
    foreign key(FILESYSTEM_ID) references FILESYSTEM_INFO(FILESYSTEM_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(FILESYSTEM_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table FILESYSTEM_AGGREGATE_MONTH (
    FILESYSTEM_ID   integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    OST_AGGREGATE   float,
    OST_MINVAL      float,
    OST_MAXVAL      float,
    OST_AVERAGE     float,
    primary key (FILESYSTEM_ID,TS_ID,VARIABLE_ID),
    foreign key(FILESYSTEM_ID) references FILESYSTEM_INFO(FILESYSTEM_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(FILESYSTEM_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
create table FILESYSTEM_AGGREGATE_YEAR (
    FILESYSTEM_ID   integer         not null,
    TS_ID           int unsigned    not null,
    VARIABLE_ID     integer         not null,
    OST_AGGREGATE   float,
    OST_MINVAL      float,
    OST_MAXVAL      float,
    OST_AVERAGE     float,
    primary key (FILESYSTEM_ID,TS_ID,VARIABLE_ID),
    foreign key(FILESYSTEM_ID) references FILESYSTEM_INFO(FILESYSTEM_ID),
    foreign key(TS_ID) references TIMESTAMP_INFO(TS_ID),
    foreign key(VARIABLE_ID) references OST_VARIABLE_INFO(VARIABLE_ID),
    index(FILESYSTEM_ID),
    index(TS_ID),
    index(VARIABLE_ID)
);
    
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('open', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('close', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('mknod', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('link', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('unlink', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('mkdir', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('rmdir', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('rename', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('getxattr', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('setxattr', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('iocontrol', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('get_info', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('set_info_async', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('attach', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('detach', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('setup', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('precleanup', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('cleanup', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('process_config', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('postrecov', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('add_conn', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('del_conn', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('connect', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('reconnect', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('disconnect', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('statfs', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('statfs_async', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('packmd', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('unpackmd', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('checkmd', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('preallocate', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('precreate', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('create', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('destroy', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('setattr', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('setattr_async', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('getattr', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('getattr_async', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('brw', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('brw_async', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('prep_async_page', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('reget_short_lock', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('release_short_lock', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('queue_async_io', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('queue_group_io', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('trigger_group_io', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('set_async_flags', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('teardown_async_page', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('merge_lvb', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('adjust_kms', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('punch', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('sync', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('migrate', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('copy', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('iterate', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('preprw', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('commitrw', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('enqueue', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('match', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('change_cbdata', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('cancel', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('cancel_unused', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('join_lru', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('init_export', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('destroy_export', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('extent_calc', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('llog_init', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('llog_finish', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('pin', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('unpin', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('import_event', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('notify', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('health_check', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('quotacheck', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('quotactl', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('quota_adjust_quint', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('ping', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('register_page_removal_cb', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('unregister_page_removal_cb', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('register_lock_cancel_cb', 'reqs');
insert into OPERATION_INFO (OPERATION_NAME, UNITS) values ('unregister_lock_cancel_cb', 'reqs');
insert into OSS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('PCT_MEM','%Mem', 0);
insert into OSS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('READ_RATE','Read Rate', 0);
insert into OSS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('WRITE_RATE','Write Rate', 0);
insert into OSS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('ACTUAL_RATE','Actual Rate', 0);
insert into OSS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1) values ('LINK_STATUS','Link Status',      1,  1.);
insert into OSS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_CPU',     '%CPU',           3, 90., 101.);
insert into OSS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('ERROR_COUNT', 'Error Count',    3,  1., 100.);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('READ_BYTES','Bytes Read', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('WRITE_BYTES','Bytes Written', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('READ_RATE', 'Read Rate', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('WRITE_RATE', 'Write Rate', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('KBYTES_FREE', 'KB Free', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('KBYTES_USED', 'KB Used', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('INODES_FREE', 'Inodes Free', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('INODES_USED', 'Inodes Used', 0);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_CPU',    '%CPU',    3, 90., 101.);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_KBYTES', '%KB',     3, 95., 100.);
insert into OST_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_INODES', '%Inodes', 3, 95., 100.);
insert into MDS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('KBYTES_FREE','KB Free', 0);
insert into MDS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('KBYTES_USED','KB Used', 0);
insert into MDS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('INODES_FREE','Inodes Free', 0);
insert into MDS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('INODES_USED','Inodes Used', 0);
insert into MDS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_CPU',    '%CPU',    3, 90., 101.);
insert into MDS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_KBYTES', '%KB',     3, 95., 100.);
insert into MDS_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_INODES', '%Inodes', 3, 95., 100.);
insert into ROUTER_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('BYTES','Bytes', 0);
insert into ROUTER_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE) values ('RATE', 'Rate', 0);
insert into ROUTER_VARIABLE_INFO (VARIABLE_NAME,VARIABLE_LABEL,THRESH_TYPE, THRESH_VAL1, THRESH_VAL2) values ('PCT_CPU', '%CPU', 3, 90., 101.);
#
# LMT2 SCHEMA 1.1 - end
#
insert into FILESYSTEM_INFO (FILESYSTEM_NAME, FILESYSTEM_MOUNT_NAME, SCHEMA_VERSION) values ('test', '', '1.1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5a1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5a2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5a3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5a4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5b1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5b2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5b3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5b4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5c1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5c2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5c3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss5c4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6a1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6a2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6a3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6a4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6b1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6b2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6b3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6b4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6c1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6c2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6c3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss6c4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7a1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7a2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7a3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7a4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7b1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7b2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7b3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7b4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7c1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7c2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7c3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss7c4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8a1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8a2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8a3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8a4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8b1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8b2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8b3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8b4');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8c1');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8c2');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8c3');
insert into OSS_INFO (FILESYSTEM_ID, HOSTNAME) values ('1', 'test-oss8c4');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a1'), 'test-OST0000', 'test-oss5a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a2'), 'test-OST0001', 'test-oss5a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a3'), 'test-OST0002', 'test-oss5a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a4'), 'test-OST0003', 'test-oss5a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b1'), 'test-OST0004', 'test-oss5b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b2'), 'test-OST0005', 'test-oss5b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b3'), 'test-OST0006', 'test-oss5b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b4'), 'test-OST0007', 'test-oss5b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c1'), 'test-OST0008', 'test-oss5c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c2'), 'test-OST0009', 'test-oss5c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c3'), 'test-OST000a', 'test-oss5c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c4'), 'test-OST000b', 'test-oss5c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a1'), 'test-OST000c', 'test-oss6a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a2'), 'test-OST000d', 'test-oss6a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a3'), 'test-OST000e', 'test-oss6a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a4'), 'test-OST000f', 'test-oss6a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b1'), 'test-OST0010', 'test-oss6b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b2'), 'test-OST0011', 'test-oss6b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b3'), 'test-OST0012', 'test-oss6b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b4'), 'test-OST0013', 'test-oss6b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c1'), 'test-OST0014', 'test-oss6c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c2'), 'test-OST0015', 'test-oss6c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c3'), 'test-OST0016', 'test-oss6c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c4'), 'test-OST0017', 'test-oss6c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a1'), 'test-OST0018', 'test-oss7a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a2'), 'test-OST0019', 'test-oss7a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a3'), 'test-OST001a', 'test-oss7a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a4'), 'test-OST001b', 'test-oss7a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b1'), 'test-OST001c', 'test-oss7b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b2'), 'test-OST001d', 'test-oss7b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b3'), 'test-OST001e', 'test-oss7b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b4'), 'test-OST001f', 'test-oss7b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c1'), 'test-OST0020', 'test-oss7c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c2'), 'test-OST0021', 'test-oss7c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c3'), 'test-OST0022', 'test-oss7c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c4'), 'test-OST0023', 'test-oss7c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a1'), 'test-OST0024', 'test-oss8a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a2'), 'test-OST0025', 'test-oss8a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a3'), 'test-OST0026', 'test-oss8a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a4'), 'test-OST0027', 'test-oss8a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b1'), 'test-OST0028', 'test-oss8b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b2'), 'test-OST0029', 'test-oss8b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b3'), 'test-OST002a', 'test-oss8b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b4'), 'test-OST002b', 'test-oss8b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c1'), 'test-OST002c', 'test-oss8c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c2'), 'test-OST002d', 'test-oss8c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c3'), 'test-OST002e', 'test-oss8c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c4'), 'test-OST002f', 'test-oss8c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a1'), 'test-OST0030', 'test-oss5a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a2'), 'test-OST0031', 'test-oss5a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a3'), 'test-OST0032', 'test-oss5a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a4'), 'test-OST0033', 'test-oss5a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b1'), 'test-OST0034', 'test-oss5b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b2'), 'test-OST0035', 'test-oss5b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b3'), 'test-OST0036', 'test-oss5b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b4'), 'test-OST0037', 'test-oss5b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c1'), 'test-OST0038', 'test-oss5c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c2'), 'test-OST0039', 'test-oss5c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c3'), 'test-OST003a', 'test-oss5c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c4'), 'test-OST003b', 'test-oss5c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a1'), 'test-OST003c', 'test-oss6a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a2'), 'test-OST003d', 'test-oss6a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a3'), 'test-OST003e', 'test-oss6a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a4'), 'test-OST003f', 'test-oss6a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b1'), 'test-OST0040', 'test-oss6b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b2'), 'test-OST0041', 'test-oss6b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b3'), 'test-OST0042', 'test-oss6b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b4'), 'test-OST0043', 'test-oss6b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c1'), 'test-OST0044', 'test-oss6c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c2'), 'test-OST0045', 'test-oss6c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c3'), 'test-OST0046', 'test-oss6c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c4'), 'test-OST0047', 'test-oss6c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a1'), 'test-OST0048', 'test-oss7a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a2'), 'test-OST0049', 'test-oss7a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a3'), 'test-OST004a', 'test-oss7a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a4'), 'test-OST004b', 'test-oss7a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b1'), 'test-OST004c', 'test-oss7b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b2'), 'test-OST004d', 'test-oss7b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b3'), 'test-OST004e', 'test-oss7b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b4'), 'test-OST004f', 'test-oss7b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c1'), 'test-OST0050', 'test-oss7c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c2'), 'test-OST0051', 'test-oss7c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c3'), 'test-OST0052', 'test-oss7c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c4'), 'test-OST0053', 'test-oss7c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a1'), 'test-OST0054', 'test-oss8a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a2'), 'test-OST0055', 'test-oss8a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a3'), 'test-OST0056', 'test-oss8a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a4'), 'test-OST0057', 'test-oss8a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b1'), 'test-OST0058', 'test-oss8b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b2'), 'test-OST0059', 'test-oss8b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b3'), 'test-OST005a', 'test-oss8b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b4'), 'test-OST005b', 'test-oss8b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c1'), 'test-OST005c', 'test-oss8c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c2'), 'test-OST005d', 'test-oss8c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c3'), 'test-OST005e', 'test-oss8c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c4'), 'test-OST005f', 'test-oss8c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a1'), 'test-OST0060', 'test-oss5a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a2'), 'test-OST0061', 'test-oss5a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a3'), 'test-OST0062', 'test-oss5a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a4'), 'test-OST0063', 'test-oss5a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b1'), 'test-OST0064', 'test-oss5b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b2'), 'test-OST0065', 'test-oss5b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b3'), 'test-OST0066', 'test-oss5b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b4'), 'test-OST0067', 'test-oss5b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c1'), 'test-OST0068', 'test-oss5c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c2'), 'test-OST0069', 'test-oss5c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c3'), 'test-OST006a', 'test-oss5c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c4'), 'test-OST006b', 'test-oss5c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a1'), 'test-OST006c', 'test-oss6a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a2'), 'test-OST006d', 'test-oss6a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a3'), 'test-OST006e', 'test-oss6a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a4'), 'test-OST006f', 'test-oss6a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b1'), 'test-OST0070', 'test-oss6b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b2'), 'test-OST0071', 'test-oss6b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b3'), 'test-OST0072', 'test-oss6b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b4'), 'test-OST0073', 'test-oss6b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c1'), 'test-OST0074', 'test-oss6c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c2'), 'test-OST0075', 'test-oss6c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c3'), 'test-OST0076', 'test-oss6c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c4'), 'test-OST0077', 'test-oss6c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a1'), 'test-OST0078', 'test-oss7a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a2'), 'test-OST0079', 'test-oss7a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a3'), 'test-OST007a', 'test-oss7a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a4'), 'test-OST007b', 'test-oss7a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b1'), 'test-OST007c', 'test-oss7b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b2'), 'test-OST007d', 'test-oss7b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b3'), 'test-OST007e', 'test-oss7b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b4'), 'test-OST007f', 'test-oss7b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c1'), 'test-OST0080', 'test-oss7c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c2'), 'test-OST0081', 'test-oss7c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c3'), 'test-OST0082', 'test-oss7c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c4'), 'test-OST0083', 'test-oss7c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a1'), 'test-OST0084', 'test-oss8a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a2'), 'test-OST0085', 'test-oss8a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a3'), 'test-OST0086', 'test-oss8a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a4'), 'test-OST0087', 'test-oss8a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b1'), 'test-OST0088', 'test-oss8b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b2'), 'test-OST0089', 'test-oss8b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b3'), 'test-OST008a', 'test-oss8b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b4'), 'test-OST008b', 'test-oss8b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c1'), 'test-OST008c', 'test-oss8c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c2'), 'test-OST008d', 'test-oss8c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c3'), 'test-OST008e', 'test-oss8c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c4'), 'test-OST008f', 'test-oss8c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a1'), 'test-OST0090', 'test-oss5a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a2'), 'test-OST0091', 'test-oss5a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a3'), 'test-OST0092', 'test-oss5a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a4'), 'test-OST0093', 'test-oss5a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b1'), 'test-OST0094', 'test-oss5b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b2'), 'test-OST0095', 'test-oss5b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b3'), 'test-OST0096', 'test-oss5b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b4'), 'test-OST0097', 'test-oss5b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c1'), 'test-OST0098', 'test-oss5c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c2'), 'test-OST0099', 'test-oss5c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c3'), 'test-OST009a', 'test-oss5c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c4'), 'test-OST009b', 'test-oss5c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a1'), 'test-OST009c', 'test-oss6a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a2'), 'test-OST009d', 'test-oss6a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a3'), 'test-OST009e', 'test-oss6a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a4'), 'test-OST009f', 'test-oss6a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b1'), 'test-OST00a0', 'test-oss6b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b2'), 'test-OST00a1', 'test-oss6b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b3'), 'test-OST00a2', 'test-oss6b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b4'), 'test-OST00a3', 'test-oss6b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c1'), 'test-OST00a4', 'test-oss6c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c2'), 'test-OST00a5', 'test-oss6c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c3'), 'test-OST00a6', 'test-oss6c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c4'), 'test-OST00a7', 'test-oss6c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a1'), 'test-OST00a8', 'test-oss7a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a2'), 'test-OST00a9', 'test-oss7a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a3'), 'test-OST00aa', 'test-oss7a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a4'), 'test-OST00ab', 'test-oss7a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b1'), 'test-OST00ac', 'test-oss7b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b2'), 'test-OST00ad', 'test-oss7b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b3'), 'test-OST00ae', 'test-oss7b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b4'), 'test-OST00af', 'test-oss7b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c1'), 'test-OST00b0', 'test-oss7c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c2'), 'test-OST00b1', 'test-oss7c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c3'), 'test-OST00b2', 'test-oss7c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c4'), 'test-OST00b3', 'test-oss7c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a1'), 'test-OST00b4', 'test-oss8a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a2'), 'test-OST00b5', 'test-oss8a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a3'), 'test-OST00b6', 'test-oss8a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a4'), 'test-OST00b7', 'test-oss8a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b1'), 'test-OST00b8', 'test-oss8b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b2'), 'test-OST00b9', 'test-oss8b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b3'), 'test-OST00ba', 'test-oss8b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b4'), 'test-OST00bb', 'test-oss8b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c1'), 'test-OST00bc', 'test-oss8c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c2'), 'test-OST00bd', 'test-oss8c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c3'), 'test-OST00be', 'test-oss8c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c4'), 'test-OST00bf', 'test-oss8c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a1'), 'test-OST00c0', 'test-oss5a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a2'), 'test-OST00c1', 'test-oss5a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a3'), 'test-OST00c2', 'test-oss5a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a4'), 'test-OST00c3', 'test-oss5a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b1'), 'test-OST00c4', 'test-oss5b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b2'), 'test-OST00c5', 'test-oss5b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b3'), 'test-OST00c6', 'test-oss5b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b4'), 'test-OST00c7', 'test-oss5b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c1'), 'test-OST00c8', 'test-oss5c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c2'), 'test-OST00c9', 'test-oss5c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c3'), 'test-OST00ca', 'test-oss5c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c4'), 'test-OST00cb', 'test-oss5c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a1'), 'test-OST00cc', 'test-oss6a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a2'), 'test-OST00cd', 'test-oss6a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a3'), 'test-OST00ce', 'test-oss6a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a4'), 'test-OST00cf', 'test-oss6a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b1'), 'test-OST00d0', 'test-oss6b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b2'), 'test-OST00d1', 'test-oss6b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b3'), 'test-OST00d2', 'test-oss6b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b4'), 'test-OST00d3', 'test-oss6b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c1'), 'test-OST00d4', 'test-oss6c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c2'), 'test-OST00d5', 'test-oss6c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c3'), 'test-OST00d6', 'test-oss6c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c4'), 'test-OST00d7', 'test-oss6c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a1'), 'test-OST00d8', 'test-oss7a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a2'), 'test-OST00d9', 'test-oss7a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a3'), 'test-OST00da', 'test-oss7a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a4'), 'test-OST00db', 'test-oss7a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b1'), 'test-OST00dc', 'test-oss7b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b2'), 'test-OST00dd', 'test-oss7b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b3'), 'test-OST00de', 'test-oss7b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b4'), 'test-OST00df', 'test-oss7b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c1'), 'test-OST00e0', 'test-oss7c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c2'), 'test-OST00e1', 'test-oss7c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c3'), 'test-OST00e2', 'test-oss7c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c4'), 'test-OST00e3', 'test-oss7c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a1'), 'test-OST00e4', 'test-oss8a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a2'), 'test-OST00e5', 'test-oss8a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a3'), 'test-OST00e6', 'test-oss8a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a4'), 'test-OST00e7', 'test-oss8a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b1'), 'test-OST00e8', 'test-oss8b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b2'), 'test-OST00e9', 'test-oss8b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b3'), 'test-OST00ea', 'test-oss8b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b4'), 'test-OST00eb', 'test-oss8b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c1'), 'test-OST00ec', 'test-oss8c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c2'), 'test-OST00ed', 'test-oss8c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c3'), 'test-OST00ee', 'test-oss8c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c4'), 'test-OST00ef', 'test-oss8c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a1'), 'test-OST00f0', 'test-oss5a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a2'), 'test-OST00f1', 'test-oss5a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a3'), 'test-OST00f2', 'test-oss5a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a4'), 'test-OST00f3', 'test-oss5a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b1'), 'test-OST00f4', 'test-oss5b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b2'), 'test-OST00f5', 'test-oss5b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b3'), 'test-OST00f6', 'test-oss5b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b4'), 'test-OST00f7', 'test-oss5b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c1'), 'test-OST00f8', 'test-oss5c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c2'), 'test-OST00f9', 'test-oss5c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c3'), 'test-OST00fa', 'test-oss5c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c4'), 'test-OST00fb', 'test-oss5c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a1'), 'test-OST00fc', 'test-oss6a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a2'), 'test-OST00fd', 'test-oss6a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a3'), 'test-OST00fe', 'test-oss6a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a4'), 'test-OST00ff', 'test-oss6a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b1'), 'test-OST0100', 'test-oss6b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b2'), 'test-OST0101', 'test-oss6b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b3'), 'test-OST0102', 'test-oss6b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b4'), 'test-OST0103', 'test-oss6b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c1'), 'test-OST0104', 'test-oss6c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c2'), 'test-OST0105', 'test-oss6c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c3'), 'test-OST0106', 'test-oss6c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c4'), 'test-OST0107', 'test-oss6c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a1'), 'test-OST0108', 'test-oss7a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a2'), 'test-OST0109', 'test-oss7a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a3'), 'test-OST010a', 'test-oss7a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a4'), 'test-OST010b', 'test-oss7a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b1'), 'test-OST010c', 'test-oss7b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b2'), 'test-OST010d', 'test-oss7b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b3'), 'test-OST010e', 'test-oss7b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b4'), 'test-OST010f', 'test-oss7b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c1'), 'test-OST0110', 'test-oss7c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c2'), 'test-OST0111', 'test-oss7c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c3'), 'test-OST0112', 'test-oss7c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c4'), 'test-OST0113', 'test-oss7c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a1'), 'test-OST0114', 'test-oss8a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a2'), 'test-OST0115', 'test-oss8a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a3'), 'test-OST0116', 'test-oss8a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a4'), 'test-OST0117', 'test-oss8a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b1'), 'test-OST0118', 'test-oss8b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b2'), 'test-OST0119', 'test-oss8b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b3'), 'test-OST011a', 'test-oss8b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b4'), 'test-OST011b', 'test-oss8b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c1'), 'test-OST011c', 'test-oss8c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c2'), 'test-OST011d', 'test-oss8c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c3'), 'test-OST011e', 'test-oss8c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c4'), 'test-OST011f', 'test-oss8c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a1'), 'test-OST0120', 'test-oss5a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a2'), 'test-OST0121', 'test-oss5a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a3'), 'test-OST0122', 'test-oss5a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5a4'), 'test-OST0123', 'test-oss5a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b1'), 'test-OST0124', 'test-oss5b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b2'), 'test-OST0125', 'test-oss5b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b3'), 'test-OST0126', 'test-oss5b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5b4'), 'test-OST0127', 'test-oss5b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c1'), 'test-OST0128', 'test-oss5c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c2'), 'test-OST0129', 'test-oss5c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c3'), 'test-OST012a', 'test-oss5c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss5c4'), 'test-OST012b', 'test-oss5c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a1'), 'test-OST012c', 'test-oss6a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a2'), 'test-OST012d', 'test-oss6a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a3'), 'test-OST012e', 'test-oss6a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6a4'), 'test-OST012f', 'test-oss6a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b1'), 'test-OST0130', 'test-oss6b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b2'), 'test-OST0131', 'test-oss6b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b3'), 'test-OST0132', 'test-oss6b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6b4'), 'test-OST0133', 'test-oss6b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c1'), 'test-OST0134', 'test-oss6c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c2'), 'test-OST0135', 'test-oss6c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c3'), 'test-OST0136', 'test-oss6c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss6c4'), 'test-OST0137', 'test-oss6c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a1'), 'test-OST0138', 'test-oss7a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a2'), 'test-OST0139', 'test-oss7a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a3'), 'test-OST013a', 'test-oss7a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7a4'), 'test-OST013b', 'test-oss7a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b1'), 'test-OST013c', 'test-oss7b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b2'), 'test-OST013d', 'test-oss7b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b3'), 'test-OST013e', 'test-oss7b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7b4'), 'test-OST013f', 'test-oss7b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c1'), 'test-OST0140', 'test-oss7c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c2'), 'test-OST0141', 'test-oss7c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c3'), 'test-OST0142', 'test-oss7c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss7c4'), 'test-OST0143', 'test-oss7c4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a1'), 'test-OST0144', 'test-oss8a1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a2'), 'test-OST0145', 'test-oss8a2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a3'), 'test-OST0146', 'test-oss8a3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8a4'), 'test-OST0147', 'test-oss8a4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b1'), 'test-OST0148', 'test-oss8b1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b2'), 'test-OST0149', 'test-oss8b2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b3'), 'test-OST014a', 'test-oss8b3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8b4'), 'test-OST014b', 'test-oss8b4', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c1'), 'test-OST014c', 'test-oss8c1', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c2'), 'test-OST014d', 'test-oss8c2', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c3'), 'test-OST014e', 'test-oss8c3', '', '0');
insert into OST_INFO (OSS_ID, OST_NAME, HOSTNAME, DEVICE_NAME, OFFLINE) values ((select OSS_ID from OSS_INFO where HOSTNAME='test-oss8c4'), 'test-OST014f', 'test-oss8c4', '', '0');
