stages:
  - build
  - test

build lmt:
  stage: build
  variables:
    FF_ENABLE_JOB_CLEANUP:
      value: "1"
  tags:
    - shell
    - tyche3
  script:
    sh autogen.sh && ./configure && make

test lmt:
  stage: test
  tags:
    - shell
    - tyche3
  script:
    make -C test check
